const DATA_FILE='catalogue.json';
let DATA={hotels:[],settings:{}}, activeCategory='';
const $=id=>document.getElementById(id);
const CAT_ABBR={'Coffee Break':'CB','Breakfast':'BR','Buffet':'BF','Canapés':'CN','Set Menu':'SM','Beverage':'BV','Meeting Package':'MP','Family Style':'FS'};
function safeNum(v){const n=Number(String(v??'').replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:0}
function enrich(payload){const p=payload&&Array.isArray(payload.hotels)?payload:{hotels:[],settings:{}};p.settings=p.settings||{};p.hotels.forEach(h=>{h.categories=Array.isArray(h.categories)?h.categories:[];const prices=h.categories.map(c=>safeNum(c.average_price_qar)).filter(Boolean);h.from_price=prices.length?Math.min(...prices):0;h.overall_average=prices.length?Math.round(prices.reduce((a,b)=>a+b,0)/prices.length):0});return p}
async function load(){try{const r=await fetch(DATA_FILE+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);DATA=enrich(await r.json());if(!DATA.hotels.length)throw new Error('catalogue.json contains no hotels');$('statusText').textContent='Live · catalogue data connected';$('statusDot').classList.add('live-on');if(DATA.settings.events_upload_url){$('eventsBtn').href=DATA.settings.events_upload_url;$('eventsBtn').style.display='inline-flex'}updateStats();render()}catch(err){console.error(err);$('statusText').textContent='Catalogue connection error';$('resultCount').textContent='The site could not read catalogue.json.';$('grid').innerHTML='<div class="empty"><b>Catalogue data is not connected.</b><br>Open <a href="CONNECTION_TEST.html">CONNECTION_TEST.html</a> for diagnosis.</div>'}}
function updateStats(){const cats=[...new Set(DATA.hotels.flatMap(h=>h.categories.map(c=>c.category)))];const prices=DATA.hotels.flatMap(h=>h.categories.map(c=>safeNum(c.average_price_qar))).filter(Boolean);$('statHotels').textContent=DATA.hotels.length;$('statCategories').textContent=cats.length;$('statAvg').textContent=prices.length?'QAR '+Math.round(prices.reduce((a,b)=>a+b,0)/prices.length):'—';$('statRange').textContent=prices.length?Math.min(...prices)+'–'+Math.max(...prices):'—'}
function categories(){return [...new Set(DATA.hotels.flatMap(h=>h.categories.map(c=>c.category)))].sort()}
function maxPrice(){return Math.max(...DATA.hotels.flatMap(h=>h.categories.map(c=>safeNum(c.average_price_qar))),1)}
function renderFilters(){const cs=categories();$('filters').innerHTML=['<button class="filter-chip '+(!activeCategory?'active':'')+'" data-cat="">All categories</button>',...cs.map(c=>'<button class="filter-chip '+(activeCategory===c?'active':'')+'" data-cat="'+escapeHtml(c)+'">'+escapeHtml(c)+'</button>')].join('');$('filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;render()})}
function hotelsFiltered(){const q=$('search').value.trim().toLowerCase();let hs=DATA.hotels.map(h=>{const matchesHotel=!q||h.supplier.toLowerCase().includes(q)||(h.meeting_spaces_note||'').toLowerCase().includes(q);const cats=h.categories.filter(c=>(!activeCategory||c.category===activeCategory)&&(!q||matchesHotel||c.category.toLowerCase().includes(q)));return {...h,categories:cats,_matchesHotel:matchesHotel}}).filter(h=>activeCategory?h.categories.length:(h._matchesHotel||h.categories.length));const sort=$('sort').value;if(sort==='price')hs.sort((a,b)=>(a.from_price||999999)-(b.from_price||999999));else if(sort==='average')hs.sort((a,b)=>(a.overall_average||999999)-(b.overall_average||999999));else hs.sort((a,b)=>a.supplier.localeCompare(b.supplier));return hs}
function render(){renderFilters();const hs=hotelsFiltered(),mx=maxPrice();$('resultCount').textContent=hs.length+' venue'+(hs.length===1?'':'s')+' shown';$('grid').innerHTML=hs.length?hs.map(h=>hotelCard(h,mx)).join(''):'<div class="empty"><b>No matching venues.</b><br>Try another hotel name or catering category.</div>'}
function hotelCard(h,mx){const meeting=h.meeting_spaces_url?'<a class="venue-link" href="'+attr(h.meeting_spaces_url)+'" target="_blank" rel="noopener">Meeting spaces ↗</a>':'';const hotelAttachment=h.hotel_attachment_url?'<a class="venue-link" href="'+attr(h.hotel_attachment_url)+'" target="_blank" rel="noopener">'+escapeHtml(h.hotel_attachment_label||'Venue attachment')+' ↗</a>':'';const count='<span class="count-badge">'+h.categories.length+' menu categor'+(h.categories.length===1?'y':'ies')+'</span>';const note=h.meeting_spaces_note?'<div class="venue-note">'+escapeHtml(h.meeting_spaces_note)+'</div>':'';const cats=h.categories.length?'<div class="category-list">'+h.categories.map(c=>categoryRow(c,mx)).join('')+'</div>':'<div class="hotel-empty">No catering menu has been attached to this venue yet. Events can add the first menu through the upload form without editing the website.</div>';return '<article class="hotel-card"><div class="hotel-band"></div><div class="hotel-header"><div class="hotel-title"><h3>'+escapeHtml(h.supplier)+'</h3><span class="tier">'+escapeHtml(h.tier||'Preferred')+'</span></div><div class="hotel-summary"><div class="from">Starting catering price <strong>'+(h.from_price?'QAR '+h.from_price:'Price on request')+'</strong></div></div></div><div class="venue-links">'+meeting+hotelAttachment+count+note+'</div>'+cats+'</article>'}
function categoryRow(c,mx){const price=safeNum(c.average_price_qar),pct=price?Math.max(8,Math.min(100,Math.round((price/mx)*100))):0,hasMenu=!!c.menu_url;const tag=CAT_ABBR[c.category]||c.category.slice(0,2).toUpperCase();const href=hasMenu?attr(c.menu_url):'#';return '<a class="category-link" href="'+href+'" '+(hasMenu?'target="_blank" rel="noopener"':'onclick="return false"')+'><span class="category-icon">'+escapeHtml(tag)+'</span><span class="category-name">'+escapeHtml(c.category)+'</span><span class="price-block"><strong>'+(price?'QAR '+Math.round(price):'Price on request')+'</strong><span>'+(price?'average / person':'Finance pricing pending')+'</span><div class="price-track"><i style="width:'+pct+'%"></i></div></span><span class="menu-action">'+(hasMenu?'View menu ↗':'Link not added')+'</span></a>'}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function attr(s){return escapeHtml(s)}
$('search').addEventListener('input',render);$('sort').addEventListener('change',render);load();
